name: Pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  pr:
    name: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i
        

      - name: Lint
        run: npm run lint

      - name: Test units
        run: npm run test